version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: password
      MSSQL_PID: Express
      MSSQL_USER: user
      MSSQL_PASSWORD: password
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql-server/data
      - ./log:/var/opt/mssql-server/log
      - ./secrets:/var/opt/mssql-server/secrets